### ISSUE TITLE
Document all attributes (e.g. show_label, show_help)

### ISSUE THREAD

**Issue by goetzb** [dyve/django-bootstrap3#139]
When migrating an existing form, I needed to turn off the display of labels. First I thought it is not possible with django-bbotstrap3 because no such option was listed on http://django-bootstrap3.readthedocs.org/en/latest/_modules/bootstrap3/templatetags/bootstrap3.html#bootstrap_field or http://django-bootstrap3.readthedocs.org/en/latest/settings.html. But then I looked at https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/renderers.py and found that you can use more options than included in the documentation, such as show_label, show_help.

I am happy to help with the documentation - I guess the "FIXTHIS" in the source is a hint that some details are missing. Perhaps I find time to expand some examples in the code to include more options.

**Comment by dyve** [comment]
Closing old issues. Improvement to docs are always welcome (and easy pull requests to make).
