### ISSUE TITLE
Bad HTML in select title attribute

### ISSUE THREAD

**Issue by dhull** [dyve/django-bootstrap3#142]
I'm getting a select element where quotes in the title element are not being escaped. For example,
```
<select multiple="multiple" class="form-control" id="id_brands" name="brands"
        title=" Hold down "Control", or "Command" on a Mac, to select more than one.">
```
This seems to be due to FieldRenderer.add_help_attrs in renderers.py. The problem goes away if I change the line
```
  self.widget.attrs['title'] = title
```
to
```
  self.widget.attrs['title'] = "" + title
```
but I haven't looked at the code carefully enough to understand why.

**Comment by chromakey** [comment]
I'm running Django 1.6 and django-bootstrap3 5.1.1 and I can't reproduce the issue.  I tried to reproduce it by placing the following in one of my form declarations:

`self.fields['field_name'].widget.attrs = {'title': ' Hold down "Control", or "Command" on a Mac, to select more than one.'}`

It rendered in HTML as:

`<select class="form-control" id="id_field_name" name="field_name" title=" Hold down &quot;Control&quot;, or &quot;Command&quot; on a Mac, to select more than one.">
</select>`

The text appears correctly when the field is hovered over.

**Comment by dyve** [comment]
Seems fine then. Closing old issues. Feel free to file a new issue, or even better, a pull request with tests!
