### ISSUE TITLE
Add setting for "default layout for form rendering"

### ISSUE THREAD

**Issue by MaZZly** [dyve/django-bootstrap3#154]
Feels kind of repetitive to add layout='horizontal' to all the 
```
{% bootstrap_form %}
{% bootstrap_formset %}
{% buttons %}
```

Should be possible in settings.py to do:
```
BOOTSTRAP3 = {
    'default_render_layout': 'horizontal',
    ...
}
```

**Comment by dyve** [comment]
Resolved with renderers. Sorry this was open for so long, should have been closed ages ago.

**Comment by MaZZly** [comment]
@dyve Sorry if I didn't read the docs well enough, but what should I specify in the settings to get the default  rendering use layount='horizontal' without specifying it on every render tag?

**Comment by MaZZly** [comment]
I checked the `BaseRenderer` source and saw on line 42:
```python
self.layout = kwargs.get('layout', '')
```
couldn't the fallback be set to something from settings? e.g. what I proposed in initial post.
