### ISSUE TITLE
Possibility to add attrs to form-group from forms.py

### ISSUE THREAD

**Issue by MaZZly** [dyve/django-bootstrap3#157]
No when specifying a formfield with special attrs:
```
class FooForm(forms.Form):
     bar_field = forms.CharField(widget=forms.TextInput(attrs={'class':'fooClass'}))
```
The fooClass is added onto the input field itself. Not onto the ```<div class="form-group"></div>``` wrapper. 

It would be nice to be able to specify attrs that are added to the form-group wrapper aswell.

I'm not sure as to how this should be done but either a seperate ```wrap_attrs={}``` or just simply adding the attrs to the wraper as well (will most likely cause faulty html and overall problems?)

**Comment by dyve** [comment]
Closing old issues. Sorry this didn't make it. Feel free to file a new issue, or even better, a pull request with tests!
