### ISSUE TITLE
Form Error State Rendering

### ISSUE THREAD

**Issue by troygrosfield** [dyve/django-bootstrap3#170]
When rendering a form with errors, currently each form group gets a class associated with it (either error or "has-success").  The class "has-success" attracts unwanted visual attention to fields that don't have any issues by turning the whole form group green.  Yes, green typically means good, but it also raises the question of why did every field change color.  

The proposed change here is to only add classes to form-groups that need attention (the ones that errored), which is a more common pattern on many sites.  That way, the rendered error form is more focused and less distracting.  

For other examples in the community see the screenshots below (you can pick about any site and the results will be the same):

![screen shot 2014-08-27 at 10 14 10 am](https://cloud.githubusercontent.com/assets/1551551/4063127/4208ef02-2e05-11e4-8a31-6463dac3321e.png)

![screen shot 2014-08-27 at 10 19 43 am](https://cloud.githubusercontent.com/assets/1551551/4063220/fd2f5b7c-2e05-11e4-9ce1-faaaa49a7846.png)

**Comment by dyve** [comment]
Closing old issues. Suddenly see that there is indeed duplicate code that adds the hardcoded error class. Oldest issue I ever closed, but I just fixed it in develop.
