### ISSUE TITLE
Form wizard nav tabs

### ISSUE THREAD

**Issue by danielw92** [dyve/django-bootstrap3#171]
Recently, as part of a job at my university, I implemented a custom template tag for form wizards that generates nav tabs for each step in the wizard.

This is what my example application looks like:
![image](https://cloud.githubusercontent.com/assets/7038857/4116519/f1890e60-3285-11e4-9215-00010696cba8.png)

Since those nav tabs require Bootstrap, I thought it might be a good fit for django-bootstrap3 and would like to know your opinion on this. Currently, my code is a standalone Django app, but I'd be happy to create a fork and submit a pull request.

Please let me know what you think.

**Comment by dyve** [comment]
I'm sorry this was never paid proper attention to. Your idea and execution look just fine.
