### ISSUE TITLE
Add a layout param to fields

### ISSUE THREAD

**Issue by frague59** [dyve/django-bootstrap3#175]
Add a :
```
{% bootstrap_field field layout="horizontal" %}
```
support for *bootstrap_field* or make use of 
```
BOOTSTRAP3['horizontal_label_class']
BOOSTRAP3['horizontal_label_class'] 
```
for fields.

**Comment by mollymute** [comment]
Do you mean for forms? I think the bootstrap horizontal class applies to the form as a whole.

**Comment by dyve** [comment]
Fixed with renderers a while ago. Sorry for the late reply.
