### ISSUE TITLE
Required fields set via __init_ are rendered as non-required

### ISSUE THREAD

**Issue by savvaoff** [dyve/django-bootstrap3#180]
Dylan,

if fields are set as required in form __init__ method, for ex:
"
    def __init__(self, *args, **kwargs):
        super(InvestorProfileForm, self).__init__(*args, **kwargs)
        for field in ('first_name', 'last_name', 'country', 'address1', 'country', 'postcode', 'city'):
            self.fields[field].required = True
"

such fields are not rendered as "required" (no required attribute in the tags). here is the template code:
"
        {% bootstrap_field form.country layout='horizontal' %}
        {% bootstrap_field form.address1 layout='horizontal' %}
        {% bootstrap_field form.address2 layout='horizontal' %}
"

thanks.

**Comment by beruic** [comment]
I experience that this is only a problem with FileField and ImageField. CharField works fine.

**Comment by beruic** [comment]
I have tested now, and this issue concerns both `FileField` and `ImageField` fields defined in and out of `__init__`.

I am also pretty sure I have found the solution. Remove `FileInput, ` from https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/forms.py#L173

**Comment by dyve** [comment]
All handling of `required` and `disabled` was rather hacky, and mainly because Django did not support it. In Django 1.9 and 1.10 this has been adopted, look at issues #345 and #337
