### ISSUE TITLE
Error Messaging and Help Text Collide

### ISSUE THREAD

**Issue by troygrosfield** [dyve/django-bootstrap3#182]
When a form produces an error, the help text and error messaging collide and the error messaging gets lost:

**Normal Form State**

![screen shot 2014-10-23 at 8 50 24 am](https://cloud.githubusercontent.com/assets/1551551/4755268/32536d58-5ac4-11e4-8002-2e8c031f70c4.png)

**Error Form State**

![screen shot 2014-10-23 at 8 50 51 am](https://cloud.githubusercontent.com/assets/1551551/4755279/4294ad12-5ac4-11e4-83a5-59df305036b6.png)

The error messaging **The following are not valid email addresses: "troy", "grosfield"** gets buried behind the help text.  If a form field errors, it should be the first thing visible after the form field.  

This should instead be rendered as follows:

![screen shot 2014-10-23 at 8 57 12 am](https://cloud.githubusercontent.com/assets/1551551/4755359/eab1bcec-5ac4-11e4-9f92-fa79ee57fe75.png)

The Markup for this change:

```
<div class="form-group has-error">
    <label class="control-label" for="id_email_addresses">Email Addresses</label>
    <textarea class="form-control" cols="40" id="id_email_addresses" name="email_addresses" placeholder="Email Addresses" required="required" rows="10" title="Add the comma separated list of email addresses of the people you would like to invite to join.  Example: " person1@example.com,="" person2@example.com"."="" tabindex="1">troy, grosfield</textarea>
    <div class="help-block">The following are not valid email addresses: "troy", "grosfield"</div>
    <div class="help-block">Add the comma separated list of email addresses of the people you would like to invite to join.  Example: "person1@example.com, person2@example.com".
</div></div>
```
Also, in your markup on the help text you're using a span for what should be a block level element:

**Your Help Text Markup**

```
<span class="help-block">
    Some help text
</span>
```

This should instead be:
```
<div class="help-block">
    Some help text
</div>
```

**Comment by troygrosfield** [comment]
@dyve, Any updates on this?

**Comment by dyve** [comment]
I haven't gotten around to fixing it yet. Feel free to (ask someone to) provide a pull request!

**Comment by florian-hartmann** [comment]
Pull request incoming :)

**Comment by Gillingham** [comment]
This is a fairly large issue for me, it makes django-bootstrap3 mostly useless since some fields I need help_text, but I can't enable them or all validation errors end up broken.

**Comment by b-dev** [comment]
any news?

**Comment by Matoking** [comment]
You can fix this issue by substituting the _field_help_text_and_errors.html_ template with your own one; just remember to load the app with the template fix in before _bootstrap3_. I replaced mine with this

```
{% for text in help_text_and_errors reversed %}
    <div class="help-block">{{ text }}</div>
{% endfor %}
```

Error messages are displayed first, and rest of the messages are separated with two line breaks, making it look like the example in the OP.
