### ISSUE TITLE
problem on render DateField with custom format

### ISSUE THREAD

**Issue by edgabaldi** [dyve/django-bootstrap3#189]
I have the follow form:

```
class PeriodForm(forms.Form):
    start_date = forms.DateField(input_formats=['%d/%m/%Y'], required=False)
    end_date = forms.DateField(input_formats=['%d/%m/%Y'], required=False)
```

In my template i use bootstrap template tag

```
{% bootstra_field form.start_date %}
```

I input a date: 16/11/2014, on submit, in my view, when i call the form.is_valid(), i get a form error that the format of date is invalid.

I dont saw nothing about this on documentations ou related issues.

Any idea?

**Comment by dyve** [comment]
Date input formats are handled according to Django specs. Look for Django date settings.
