### ISSUE TITLE
Render field and label

### ISSUE THREAD

**Issue by mazing** [dyve/django-bootstrap3#191]
`{% bootstrap_field form.field_name %}` renders both field and label. It would be great with a specific `bootstrap_field`, `bootstrap_label` and `bootstrap_field_and_label` just like there already exists methods for these separations.

**Comment by 57even** [comment]
The tag option show_label is good but it will still print the div element `<div class="form-group">` and the label but with the class sr-only added. I need to print only the field, e.g. `<input type="text" class="form-control" ....`

**Comment by VSandSH** [comment]
Hello, how can I display only fields without labels with bootstrap3?

**Comment by VSandSH** [comment]
Figured that out, it seems show_label needs to be in the {% ... %} and set to False.

**Comment by gilsondev** [comment]
Need update documentation to explain about show_label and others parameters.
