### ISSUE TITLE
Make "exclude" fields configurable in the form itself

### ISSUE THREAD

**Issue by troygrosfield** [dyve/django-bootstrap3#205]
I've been searching most of the day for a way to exclude fields from output and I see there's an undocumented approach by calling "exclude" from the templatetag:

```
{% bootstrap_form form exclude="cc_myself" %}
```

- https://github.com/dyve/django-bootstrap3/blob/d846fb4d54ace0338be2e057e7eca9db6bce8543/bootstrap3/tests.py#L226
- https://github.com/dyve/django-bootstrap3/blob/d846fb4d54ace0338be2e057e7eca9db6bce8543/bootstrap3/renderers.py#L36

Very cool stuff.  However, it would be great if this was configurable from the form itself and not just in the template.  That way, the excluded fields can be dynamically set when the form is initialized and the template logic doesn't need to be touched.

So, the enhancement request here would be to do something like check for a method or attribute on the form that the bootstrap template renders would look for.

```
class MyForm(forms.ModelForm):
    excluded_fields = None

    class Meta:
        model = SomeModel
        fields = ('field_1', 'field_2', 'field_3',)

    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        if not self.excluded_fields:
            self.excluded_fields = []

        self.excluded_fields.append('field_2')
````
or just add a method to the forms that gets the fields to exclude:
```
    def get_excluded_fields(self):
        return ['field_2']
```
Then have the template check the form for the ``excluded_fields`` attribute or method.  

```
class FormRenderer(BaseRenderer):
    def __init__(self, *args, **kwargs):
        ...
        if hasattr(self.form, 'excluded_fields'):
            self.exclude = self.form.excluded_fields
        ...
```

@dyve, Thoughts?

**Comment by dyve** [comment]
I think this would clash horribly with Django's ModelForm and their include/exclude syntax in the Meta class.

What you want in django-bootstrap3 is to EXCLUDE fields from the default Bootstrap3 rendering because you will render those fields in another way. f the fields are part of the form, they should be rendered.

So unless I am missing something, I wouldn't want to touch the Django form definition for this.

**Comment by dyve** [comment]
Of course the exclude filter could be better documented.

**Comment by dyve** [comment]
Documented exclude (finally)
