### ISSUE TITLE
Current page in paginator is off by one

### ISSUE THREAD

**Issue by frewsxcv** [dyve/django-bootstrap3#212]
![screen shot 2015-01-30 at 2 22 11 pm](https://cloud.githubusercontent.com/assets/416575/5981828/73b6ef76-a88b-11e4-9acf-bea74d44fdf9.png)

In this screenshot you can see that '21' is the center-most page number in the paginator, though '20' should be since it's the current page.

**Comment by frewsxcv** [comment]
If this is the intended behavior, let me know

**Comment by dyve** [comment]
Thanks, pulling (copying) this in.
