### ISSUE TITLE
How to setup rows and cols attrs with bootstrap_field?

### ISSUE THREAD

**Issue by eremeevdev** [dyve/django-bootstrap3#213]
I try to {% bootstrap_field form.message rows="5" %}, but it doesn't work

**Comment by chrisjenx** [comment]
+1

**Comment by dyve** [comment]
Not sure what was meant here. If you need HTML around your field you should write that around it.

**Comment by raelmax** [comment]
The textarea field of bootstrap use "cols" and "rows" attributes to set the textarea size. It would be nice if we can pass this by parameter to bootstrap_field templatetag, or if this template tag interprete all unknow parameters as field parameters.
