### ISSUE TITLE
How to specify the ID with bootstrap_button

### ISSUE THREAD

**Issue by munum** [dyve/django-bootstrap3#214]
Hi

Does anyone know if the ID of a button could be specify using bootstrap_button? I know it could be used to specify classes, type, etc. but it doesn't seem to accept the ID.

Thanks

**Comment by dyve** [comment]
I just checked, this could be added. I think this hasn't gotten much attention, because if you need the ID of a button it might be easier to just code the HTML instead of using `bootstrap_button`.

**Comment by dyve** [comment]
Added id option
