### ISSUE TITLE
Local Bootstrap

### ISSUE THREAD

**Issue by isn85** [dyve/django-bootstrap3#216]
Hello!
Please, tell me is it possible to use the locally stored bootstrap (not distributed by cdn)?

Thanks!

**Comment by adriaant** [comment]
Example:
```
BOOTSTRAP3 = {
    'include_jquery': False,
    'jquery_url': '/static/jquery.min.js',
    'base_url': '/static/bootstrap/',
    'css_url': '/static/bootstrap/css/bootstrap.min.css',
    'theme_url': '/static/bootstrap/css/bootstrap-theme.min.css',
    'javascript_url': '/static/bootstrap/js/bootstrap.min.js',
}
BOOTSTRAP_BASE_URL = '/static/bootstrap/'
```

**Comment by isn85** [comment]
Thanks a lot!

**Comment by vindarel** [comment]
Thanks ! I suggest you add this example [in the doc](https://django-bootstrap3.readthedocs.org/en/latest/settings.html). I didn't see mention of `bootstrap_base_url`. Cheers !
