### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by davidrenne** [dyve/django-bootstrap3#217]
https://github.com/dyve/django-bootstrap3#requirements

Needs this info:

pip install django-vanilla-views; pip install model_mommy;pip install django_webtest;pip install django-bootstrap3;

**Comment by dyve** [comment]
These are not requirements for django-bootstrap3. Only django-bootstrap3 is required. Perhaps you filed this issue on the wrong project?

**Comment by davidrenne** [comment]
Whoops I did
