### ISSUE TITLE
adding layout managment for {% bootstrap_form %}

### ISSUE THREAD

**Issue by onysos** [dyve/django-bootstrap3#220]
hi dyve, 

first, I thank you for your great apps that help us so many time...

I have a question for an enhancement, and propose to write it if it does not exists.

I have some form that could change radically for some users and config, and for the display of these forms, I must use your  `{% bootstrap_form %}` template tag.

the disadvantage with this tag, is that the layout is not customisable,it is always line after lines, et there is no way to display some fields in the same line, or event create to columns of fields. 

next you can see a form hande made using `{% bootstrap_field %}`. 

![form](https://cloud.githubusercontent.com/assets/3406733/6409233/cc04a7aa-be60-11e4-86a3-85c7e30ea398.png)

my objectif is to make the same form with only the `{% boostrap_field %}` tag, and a extra attribute in the `Form`

what do you think of that ?

ps: sorry for my bad english. not my mother tongue

**Comment by dyve** [comment]
Yes, if you do not want the entire `bootstrap_form` you can build your own form by specifying certain fields and render them manually (with or without `bootstrap_field`). Since nothing in `django-bootstrap3` tampers with the native Django forms, you can do any customization you can do with regular Django.

**Comment by onysos** [comment]
yes, it is exactly what I have done in he form you can see. 

but what I want to add, is a way to tell `{% bootstrap_form %}` how I wante my form, but without writing any HTML, only in Python. lets write a litle exemple... that should give me a form like the one you see, but with a large texterea that take all the size of the page.

## models.py
    
    class Fiche(Model):
    
        libelle = models.CharField("Société", max_length=256)
        telephone = models.CharField("Téléphone", max_length=256, blank=True, null=False)
        telephone_portable = models.CharField("Téléphone portable", max_length=256, blank=True, null=False)
        fax = models.CharField(max_length=256, blank=True, null=False)
        email = models.EmailField(blank=True, null=False)
        type = models.CharField(max_length=72, choices=CLIENT_TYPE_CHOICE, blank=False, null=False)
        frequence_visite = models.IntegerField("Fréquence de visite", choices=FREQUENCE_VISITES_CHOICE, help_text="frequence de visite en jours", default=30, blank=False, null=False)
        representant = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Représentant", null=True, blank=True, on_delete=PROTECT, related_name="fiches")
        memo = models.TextField(blank=True)
        actif = models.BooleanField(default=True, help_text="permet de cacher cette fiche")
        
        adresse = models.CharField(max_length=512, blank=True)
        adresse2 = models.CharField("Complément adresse", max_length=512, blank=True)
        code_postal = models.CharField(max_length=150)
        ville = models.CharField(max_length=512, blank=True)
        
## forms.py
    
    class MyDynamicFicheModelForm(ModelForm):
        class Meta:
            model = Fiche
            fields = settings.LIST_FIELDS_FICHE_FORM
            
        bootstrap_layout = settings.LAYOUT_FICHE_FORM
        
    
## settings.py
    
    
    LIST_FIELDS_FICHE_FORM = [
      "libelle","telephone", "telephone_portable", "fax", "email", "frequence_visite"
      "representant","memo","adresse","adresse2","code_postal","ville",
    ]
    
    LAYOUT_FICHE_FORM = [
        BSRow(
            ["libelle","telephone", "telephone_portable", "fax", "email"],
            ["frequence_visite", "representant", BSSeparator(), "adresse","adresse2", BSRow("code_postal","ville")]
        ),
        "memo"
    ]
        
## template.html

    {% bootstrap_form form use_layout="true" %}

this need is comparable to what the admin page do, and what some apps can do, but not in a bootstrap3 way.

**Comment by dyve** [comment]
This approach (defining a layout class) is probably the best one. I'm not going for it now, but will keep it in mind.
