### ISSUE TITLE
ImportWarning while atempting to import bootstrap3/templates/

### ISSUE THREAD

**Issue by Unode** [dyve/django-bootstrap3#225]
Hi all,

When running bootstrap3 normally I often get the warning `ImportWarning: Not importing directory 'site-packages/boostrap3/templates' missing __init__.py` which spams the logs.

The problem seems to be that there are two conflicting entities with the "same" name; the folder `templates/` and the file `templates.py`.

Could perhaps `templates.py` be renamed to something else to avoid this clash?

**Comment by dyve** [comment]
Thanks, maybe we can join templates.py and utils.py

**Comment by Unode** [comment]
Thanks for the quick fix.
