### ISSUE TITLE
Is there an option to add autofocus for a field ? 

### ISSUE THREAD

**Issue by karol83** [dyve/django-bootstrap3#226]
Is there currently an option to add autofocus to a given field ? Anybody else finds that usefull ? Thanks!

**Comment by dyve** [comment]
This is something that you should do with JavaScript, either native or using jQuery or another framework.

**Comment by un33k** [comment]
+1

**Comment by y2kbadbug** [comment]
What do you mean this is something that should be done with jquery or another framework?  autofocus is an actual valid attribute:

http://www.w3schools.com/tags/att_input_autofocus.asp

Why make us reinvent the wheel?  This should be reopened and re-evaluated.

I would be more understanding if it was an actual "full blown feature request", but what is being asked is for support for an actual existing and should be already included attribute.

Just my 2 cents.

**Comment by y2kbadbug** [comment]
Am I welcome to submit a pull request?

**Comment by dyve** [comment]
Hi, apologies if I misunderstood the request, I thought you meant dynamically adding autofocus (and I still say this is a JavaScript job).

Adding widget attributes such as autofocus is already fully supported. You add them in Django code:
https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#django.forms.Widget.attrs

Attributes added like this will be rendered by `django-bootstrap3`. No pull request is necessary.
