### ISSUE TITLE
maxcdn vs netdna

### ISSUE THREAD

**Issue by djangoic** [dyve/django-bootstrap3#230]
Hi Dylan - Thanks for your contribution with this module.  I have been using this and it has been a great help.  Curious about maxcdn vs netdna. Based on what I read, it seems we should be pointing to maxcdn now, although netdna works.  Wondering if it crossed your mind to change the base_url to something like '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/'

Thanks
-James

**Comment by dyve** [comment]
Looks like you're right.

**Comment by HEdingfield** [comment]
I'd also think the link should be "https://..." but maybe you disagree for performance reasons?

**Comment by dyve** [comment]
// is fine, it will do https when the page itself is fetched over https, and http if the page itself was fetched over http
