### ISSUE TITLE
Template.render should be called with a dict

### ISSUE THREAD

**Issue by afg984** [dyve/django-bootstrap3#234]
We have the following in ``bootstrap3/renderers.py``:
```python
return get_template(...).render(
    Context({
        ...
    })
)
```
while django suggests to call Template.render with a dict:
```python
        elif isinstance(context, Context):
            warnings.warn(
                "render() must be called with a dict, not a Context.",
                RemovedInDjango20Warning, stacklevel=2)
```
(https://github.com/django/django/blob/master/django/template/backends/django.py)

It still works on django templates, but breaks on other templates, such as jinja2.

**Comment by dyve** [comment]
So what is the suggested upgrade path? Add the request as a context var?

**Comment by afg984** [comment]
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#django-template-loader
I think it can be omitted since it's not a RequestContext

**Comment by dyve** [comment]
Thanks. Will see if I can make this work without offending Django < 1.8 too much

**Comment by Wtower** [comment]
Subscribing.

**Comment by dyve** [comment]
Major troubles with this. A fix is in place in the current develop branch, but it's not pretty and i have no idea how Jinja2 and others will react.
