### ISSUE TITLE
Unable to run having DEBUG=True with error You must set settings.ALLOWED_HOSTS if DEBUG is False.

### ISSUE THREAD

**Issue by o5k** [dyve/django-bootstrap3#235]
`python manage.py runserver`

> CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

I runned this command in a newly created python2.7 virtualenv in which i just installed the requirements
`pip install -r requirements.txt` and got that error.
It seems that there is a problem with the settings file located in demo folder, because it contains already `DEBUG = True`, which is contradictory.

**Comment by hjmora** [comment]
Same error here...

**Comment by mollymute** [comment]
Have you set allowed hosts to ['*']? That's fixed that problem before for me.

**Comment by adriaant** [comment]
This has nothing to do with django-bootstrap. Either you set Debug=True or you specify ALLOWED_HOSTS. Every Django project has that choice.

**Comment by AliKhyar** [comment]
verify that DEBUG isn't in docker-compose.yml, put it in Dockerfile as ENV. Then in your setting change DEBUG and ALLOWED_HOSTS with:
`DEBUG = bool(os.environ.get('DEBUG', default=False)) `
`ALLOWED_HOSTS = [ ] if DEBUG==True else ['localhost']`

**Comment by AliKhyar** [comment]
you can change env the variables from docker-compose to Dockerfile, then in your settings.py write:
`DEBUG = bool(os.environ.get('DEBUG', default=False))`
`ALLOWED_HOSTS = ['127.0.0.1'] if DEBUG==False else [ ]`
