### ISSUE TITLE
Pagination should not delete other GET variables

### ISSUE THREAD

**Issue by throwable-one** [dyve/django-bootstrap3#240]
Check querystring tag from django_tables for example of how it should work.

**Comment by dyve** [comment]
You can provide the pagination tag with the current url, and all parameters remain intact.

See demo app, 

    {% bootstrap_pagination lines url="/pagination?page=1&flop=flip" extra="q=foo" size="small" %}

**Comment by throwable-one** [comment]
Thank you, but do not you think it will be much cooler to remain current variables by default?

Some times it is not easy to reconstruct current url in template (there are some ways like http://stackoverflow.com/questions/2882490/get-the-current-url-within-a-django-template , but it is not easy) and in most cases user does not want all other variables to be resetted. 

In my app I use django-filter and django-tables2 , so I may have filter and order parameters in get string, and it will be mich better to preserve them.

**Comment by sedrubal** [comment]
I'd also think it would be best practice not to ignore other GET params by default. I currently see no advantage in ignoring them...
