### ISSUE TITLE
Pass horizontal_field_class/horizontal_label_class to specific form

### ISSUE THREAD

**Issue by samupl** [dyve/django-bootstrap3#244]
It would be great if it would be possible to pass horizontal_label_class and/or horizontal_field_class params directly to the bootstrap_form tags, instead of putting it for every form in the settings.

**Comment by Davidhidalgo** [comment]
And for the bootstrap_field!

**Comment by dyve** [comment]
Has been done a while ago, sorry this was open for so long.
