### ISSUE TITLE
add extra classes to bootstrap_button 

### ISSUE THREAD

**Issue by azreda** [dyve/django-bootstrap3#247]
It would be nice to be able to do something like

```
{% buttons submit='Update' extra_classes='pull-right' %}{% endbuttons %}
```

Related, it would be nice to document all available options (like layout, reset etc) in the docs.

**Comment by mollymute** [comment]
Are those options for buttons? I can document them if so. My pull request adds an 'extra_classes' argument to the template tag.

**Comment by dyve** [comment]
Use extra_classes as an argument. Thanks!
