### ISSUE TITLE
widgets & BootstrapTextInput, BootstrapUneditableInput

### ISSUE THREAD

**Issue by gcnl** [dyve/django-bootstrap3#250]
Hello dyve!
i can not find the widgets.BootstrapTextInput, BootstrapUneditableInput in the bootstrap3 as in the earlier version:

#from bootstrap_toolkit.widgets import BootstrapTextInput,BootstrapUneditableInput

is there an alternative way doing the same?

thanks

**Comment by dyve** [comment]
No widgets in this version. TextInput renders automatically. UneditableInput ... no replacement for that (yet). Suggestions welcome.
