### ISSUE TITLE
How do we set media to all?

### ISSUE THREAD

**Issue by niranjfantain** [dyve/django-bootstrap3#255]
In django template if we give {{ bootstrap_css }}

we get the CDN url of boostrap css, where media is set to screen

**Comment by dyve** [comment]
It look like Bootstrap has changed the preferred way to include the CSS. The examples on get bootstrap.com now indicate that the media attribute be left out entirely. Let's just follow that.

**Comment by dyve** [comment]
To Do: change bootstrap CSS links so that they do not have a media attribute

**Comment by niranjfantain** [comment]
But in django template when we include {{ bootstrap_css }}, the media attribute automatically gets added.

**Comment by dyve** [comment]
Yes, so we will have to fix that in the code. A little patience please.

**Comment by niranjfantain** [comment]
Okay sure
