### ISSUE TITLE
Don't do funky stuff with message tags, use MESSAGE_TAGS instead

### ISSUE THREAD

**Issue by aidanlister** [dyve/django-bootstrap3#257]
This can go into settings.py:

MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success success',
    messages.WARNING: 'alert-warning warning',
    messages.ERROR: 'alert-danger error'
}

**Comment by dyve** [comment]
Good idea, will investigate.

**Comment by dyve** [comment]
- This would be a global settings, and affect messages in the same Django app that were not rendered with Bootstrap.
- Also this would require a non-BOOTSTRAP setting for `django-bootstrap3` to work properly.

Since the current code seems to be working fine I'll just leave it at that.
