### ISSUE TITLE
Show field errors in {% bootstrap_form_errors %}

### ISSUE THREAD

**Issue by TyVik** [dyve/django-bootstrap3#262]
Hi! I does not see form field errors in {% bootstrap_form_errors %}. I have doubt about this code in renderers.py:
```python
    def get_fields_errors(self):
        form_errors = []
        for field in self.form:
            if field.is_hidden and field.errors:
                form_errors += field.errors
        return form_errors
```
Field errors will be shown only for hidden field. Is it correct?

**Comment by dyve** [comment]
Try the demo app and see if the field errors appear there (I am pretty sure they will). Then try to work back from there.

**Comment by TyVik** [comment]
{% bootstrap_form_errors %} use only in form_by_field.html:
```
{% bootstrap_form_errors form type='non_fields' %}
```
and show only non field errors. I try delete type argument and but nothing changes.

**Comment by dyve** [comment]
I understand what you mean. The code was originally meant to show only errors for fields that were hidden or not part of the form. The type/filter option is indeed not clear. We will need to sort this out. Thanks for reporting.
