### ISSUE TITLE
Add ability to override placeholder text on individual forms.

### ISSUE THREAD

**Issue by austintrose** [dyve/django-bootstrap3#263]
It seems like some functionality could be expanded on around [here](https://github.com/dyve/django-bootstrap3/blob/892ec6781652b12db61929217c691d91f12b70c8/bootstrap3/renderers.py#L212-L215).

**Comment by clokep** [comment]
@austintrose and I ended up writing a custom renderer to do this. There's some code below that is similar to what we used.

In some app in your project (let's call it `foo.apps.core.renderers.py`):
```python
from bootstrap3.renderers import FieldRenderer


class PlaceholderFieldRenderer(FieldRenderer):
    def __init__(self, *args, **kwargs):
        super(PlaceholderFieldRenderer, self).__init__(*args, **kwargs)

        # Now override to show the placeholder no matter what setting is used.
        self.placeholder = self.field.label
        # Remove the label so only the placeholder exists.
        self.field.label = ''
```

In your `settings.py`:
```python
# BOOTSTRAP 3 FORMS CONFIGURATION
# http://django-bootstrap3.readthedocs.org/en/latest/settings.html
BOOTSTRAP3 = {
    # Don't normally want placeholders.
    'set_placeholder': False,
}
# Add a special renderer, note this won't pick up new renderers added by upstream.
BOOTSTRAP3['field_renderers'] = {
    # Be sure to include at least 'default' or things break.
    'default': 'bootstrap3.renderers.FieldRenderer',
    'inline': 'bootstrap3.renderers.InlineFieldRenderer',
    'placeholder': 'foo.apps.core.renderers.PlaceholderFieldRenderer',
}
# END BOOTSTRAP 3 FORMS CONFIGURATION
```

In a template where you want to use this:
```html
<form>
    {% bootstrap_form form layout='placeholder' %}
</form>
```

You could also just override the `'default'` renderer to do this everywhere, but there's the `set_placeholder` option for that. :smile: 

If this seems like a sane thing to add, @austintrose or I will put up a PR with this feature.

**Comment by dyve** [comment]
I'd think adding a placeholder argument to render_field is the way to go. Comments welcome.

**Comment by RodolphoPivetta** [comment]
any setting on django-bootstrap3 to solve this already?

**Comment by dyve** [comment]
I asked for comments on my suggestion to solve this with a placeholder parameter. No replies yet.

**Comment by austintrose** [comment]
@dyve I like it :+1: Sorry, I assumed you meant comments from your core team here.

**Comment by jonashaag** [comment]
> I'd think adding a placeholder argument to render_field is the way to go. Comments welcome.

+1

**Comment by beruic** [comment]
I think this is the better solution:

    <form>
        {% bootstrap_form form set_placeholder=False %}
    </form>

to override the default setting for a single form.
The reason for this is that layout you'd expect the layout, i.e. the location of elements, to change. Placeholders are always inside the input fields, and are wither there or not, regardless of how they are layed out.

**Comment by jonashaag** [comment]
@beruic This doesn't help you set *custom* placeholders, though; it just helps you not render placeholders in the first place.

**Comment by beruic** [comment]
@jonashaag No, but it helps you disable the automatic placeholders set from the label, the few places you don't want them. According to documentation, the global `set_placeholder` does the following _# Set placeholder attributes to label if no placeholder is provided_. This behaviour can only be globally disabled, and not for the individual form, which is pretty annoying. Other settings, like `horizontal_label_class`, and `horizontal_field_class` can be overridden for each form.

**Comment by jonashaag** [comment]
@beruic Right, so maybe both changes are necessary.

**Comment by ottati** [comment]
:+1:

**Comment by Gillingham** [comment]
This is a fairly large issue for me, it makes django-bootstrap3 mostly useless since some fields I need help_text, but I can't enable them or all validation errors end up broken.

**Comment by adamcharnock** [comment]
I know its been a while, but I'd love to see this too.

**Comment by dyve** [comment]
It should have been in ages ago, but a bug prevented it from working. Pushing `placeholder` option on `bootstrap_field` to develop now.

**Comment by adamcharnock** [comment]
Amazing, thank you very much!

**Comment by adamcharnock** [comment]
@dyve Is there a possibility of this change making it into a release? It would be very useful on my current project.

**Comment by dyve** [comment]
The current development branch would break compatibility with 1.8 LTS so we need to be pretty sure to make a release now.
