### ISSUE TITLE
install warning: no files found matching '*.png' under directory 'bootstrap3'

### ISSUE THREAD

**Issue by renpj** [dyve/django-bootstrap3#268]
I got these warning during the installation:  

   warning: no files found matching '*.png' under directory 'bootstrap3'
    warning: no files found matching '*.gif' under directory 'bootstrap3'
    warning: no files found matching '*js' under directory 'bootstrap3'
    warning: no files found matching '*jpg' under directory 'bootstrap3'
    warning: no files found matching '*jpeg' under directory 'bootstrap3'
    warning: no files found matching '*svg' under directory 'bootstrap3'
    warning: no files found matching '*.png' under directory 'demo'
    warning: no files found matching '*.gif' under directory 'demo'
    warning: no files found matching '*js' under directory 'demo'
    warning: no files found matching '*jpg' under directory 'demo'
    warning: no files found matching '*jpeg' under directory 'demo'
    warning: no files found matching '*svg' under directory 'demo'

I'm using Django 1.8.2, python 2.7.6

**Comment by dyve** [comment]
You can safely ignore these. If anyone knows how to improve the sep process so these warning do not appear, I'd like to know.
