### ISSUE TITLE
required_css_class argument in {% bootstrap_form form ... %}

### ISSUE THREAD

**Issue by epineda** [dyve/django-bootstrap3#275]
Hi!

I'm trying to set required_css_class for a specific form rendering without using it like a global setting in BOOTSTRAP3.
So, when I read http://django-bootstrap3.readthedocs.org/en/latest/templatetags.html#bootstrap-form ("See bootstrap_field for other arguments") I understood that by doing this:
`{% bootstrap_form myform required_css_class='required' %}`
I get what I wanted... but it didn't work... :(

Is there a problem in bootstrap_form template tags? or am I doing something wrong?

I'm using django-bootstrap3 6.2.2

Thank you very much in advance for any help

**Comment by gordon-** [comment]
I’ve the same problem with the 'bound_css_class', passed as argument of the bootstrap_form templatetag. Those arguments are not passed to the field renderer. I’m about to send a pull request to fix this.
