### ISSUE TITLE
Deprecation warnings in django 1.9a1

### ISSUE THREAD

**Issue by jieter** [dyve/django-bootstrap3#279]
Besides #278, I get this deprication warning with django 1.9a1 and django-bootstrap  6.2.2

```
[...]site-packages/bootstrap3/utils.py:144: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(Context(context))
```

The naive solution is to remove `Context()` wrap from [this line](https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/utils.py#L142). When I do that, the warning then changes to:
```
[...]site-packages/bootstrap3/utils.py:144: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
  return template.render(context)
```

Which seems to be because of the [bootstrap_messages](https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/templatetags/bootstrap3.py#L668-L696) template tag passing the context param unchanged.

Not sure how to fix that. Just wrapping it in `dict()` seems dirty.

**Comment by Jzarecta** [comment]
Thanks for the notes, is there anything I should be concern with 1.8.2?

**Comment by jannh** [comment]
Found another Deprecation warning in Django 1.9a1:
> RemovedInDjango20Warning: django.forms.extras is deprecated. You can find SelectDateWidget in django.forms.widgets instead.

Seems to be from the renderers.py ... Unfortunately, the SelectDateWidget is not available in django.forms.widgets in Django 1.8 :(

**Comment by vakorol** [comment]
Django 1.8.6 raises `RemovedInDjango110Warning` when encounters `{% bootstrap_messages %}` in a template.

**Comment by dyve** [comment]
I think we got most of these. Closin gthis now. Please report any warning with 1 warning per issue. Thanks!
