### ISSUE TITLE
Setting show_help=False also disables tooltip

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#283]
I render some forms with `{{ bootstrap_form(template_form, layout='horizontal') }}`.

When I put `help_text='<some help text>'` on a field in the form class, the help text is shown below the input field in the rendered form, and the input field's tooltip/title shows the same text.
I don't want the text below the input field, but I would however like my users to be able to view the help from the tooltip of the input. The problem is, however, that both disappear when I render the form with `show_help=False`. It would be nice if `title` was only set on the input if `show_help` is `False`.

It would also be cool if the tooltips were rendered as actual bootstrap tooltips.

**Comment by dyve** [comment]
I will look into this, thanks.

**Comment by dyve** [comment]
The change is not too hard, but not everybody might appreciate help text being presented in the title attribute. Don't want to add another setting, so I'm parking this for now. Feel free to +1 if there is sufficient interest from other users.
