### ISSUE TITLE
Is it possible to modify a bootstrap_field's label text?

### ISSUE THREAD

**Issue by natecox** [dyve/django-bootstrap3#284]
I have an admittedly strange edge case where an existing system that I'm working on allows users to rename the labels of form fields.

I know that I can use `boostrap_label` to generate a custom label with any text, but if I do this and then render a `bootstrap_field` afterwards the label is outside of the `.form-group` and doesn't get the required class.

Is it possible to just set the label text on a `bootstrap_field` directly?

**Comment by garncarz** [comment]
I'm also experiencing this difficulty with checkboxes... I can't override their labels in a template and the original ones are shown no matter what arguments are (`show_label=False show_help=False`).

**Comment by dyve** [comment]
People, it would be a tremendous help to show a test case or a code snippet instead of just describing the effects.

**Comment by natecox** [comment]
@dyve My issue is a simple request for information on a specific topic, I don't see how a code snippet is going to help answer the question of 'is it possible to manually set the text on a `bootstrap_field` tag.

The only possibilities are 'Yes, you use the `label_text_attribute_name` attribute' or 'No, we don't currently support this'.

Going through the source, it looks like you don't support it, so I've implemented a different workaround.

**Comment by dyve** [comment]
Ah, I misunderstood then. Apologies. No, you cannot overwrite the label form the Template. The philosophy is that you set the labels in your form or view.

**Comment by natecox** [comment]
@dyve Yeah, that would be ideal. This is definitely an edge case that I'm stuck dealing with.

If I were to submit a pull request to add a label text attribute would you accept it, or do you think it's outside the scope of this project?

**Comment by dyve** [comment]
The "proper" solution would be to read the users input in the view, and then change the label of the form before rendering it with bootstrap_form or bootstrap_field. If you have the user's labels in the template, you must have also had them in the view. Unless you are doing this with JS/AJAX?

**Comment by natecox** [comment]
Long story short, the logic in the model/view layer is overly complicated and tightly coupled, and was trying defer tackling it until the next round of refactoring. It's not a big deal, it just would have been a handy feature for me to have at the moment.
