### ISSUE TITLE
importlib RemovedInDjango19Warning 

### ISSUE THREAD

**Issue by matheusjardimb** [dyve/django-bootstrap3#287]
I'm getting this warning constantly:

```lib\importlib\_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.```

I'm quite new to django/python, but it seems this lib is the source of the warning, right?
It looks like bootstrap3/bootstrap.py is still pointing to this importlib, and that is triggering the warning.

**Comment by dyve** [comment]
Not seeing this in Django 1.9.x. Please confirm this is still an issue.

**Comment by matheusjardimb** [comment]
You're right! django==1.9.2 and django-bootstrap3==6.2.2 displays no warning.
