### ISSUE TITLE
bootstrap_field template tag: Support for input group buttons

### ISSUE THREAD

**Issue by joerg86** [dyve/django-bootstrap3#295]
I have a form field (ChoiceField, rendered as select) which should have a button next to it (to preview the selected object).

See here:
http://getbootstrap.com/components/#input-groups-buttons

I have seen and tested the addon_before and addon_after options, but they of course add a span with class="input-group-addon", but I need "input-group-btn". 

Ideas: Add addon_before_class and addon_after_class which default to "input-group-addon", but can be customized. OR: Provide an option form_group=False to remove the surrounding form-group and give the user the full control (this has already been mentioned in another discussion).

Thanks,
Jörg

**Comment by amille44420** [comment]
It might be a good idea, I've a similar issue for one of my projects. I wanna add a group button to a field but I cannot do it properly with addon_before/after. Furthermore, to have a way to disable the surrounding of the field with a form group allow us to handle the surrounding, whatever the need.

**Comment by Bouni** [comment]
+1
I really would like to have this feature! Right now I do it the hacky way using jQuery:


```
$("#id_manufacturer").wrap('<div class="input-group"></div>');
$("#id_manufacturer").after('<div class="input-group-btn"> \
  <a href="#" class="btn btn-default btn-add" data-target="/manufacturer/create/"><i class="fa fa-plus "></i></a> \
  <a href="#" class="btn btn-default btn-edit disabled" data-target="/manufacturer/0/edit/"><i class="fa fa-pencil "></i></a> \
  <a href="#" class="btn btn-default btn-delete disabled" data-target="/manufacturer/0/delete/"><i class="fa fa-trash "></i></a> \
 </div>');
```

Is anybody working on this issue right now?

**Comment by neuroticnerd** [comment]
+1 this would be super useful!

**Comment by DanWright91** [comment]
I think I know how to go about implementing this feature. I like the suggestion @joerg86 made about adding an addon_before_class and addon_after_class that defaults to the existing value of "input-group-addon". I'll send a pull request when I have something working.

**Comment by dyve** [comment]
I guess this works fine, and it serves a need.

**Comment by dyve** [comment]
Pulled it in.
