### ISSUE TITLE
Option for radio-inline

### ISSUE THREAD

**Issue by chicocvenancio** [dyve/django-bootstrap3#302]
Fantastic project!
Just had to write that first.
In my project we decided to use .radio-inline instead of the usual .radio. Since we did not find and option to use it, and we can change it for the whole project as we will not use .radio anywhere we just changed ir in bootstrap3/renderers.py. But this should be handled with a new attribute or maybe a new layout 'radio-inline' perhaps.

``` python
    def post_widget_render(self, html):
        if isinstance(self.widget, RadioSelect):
            html = self.list_to_class(html, 'radio-inline')
        elif isinstance(self.widget, CheckboxSelectMultiple):
            html = self.list_to_class(html, 'checkbox')
        elif isinstance(self.widget, SelectDateWidget):
            html = self.fix_date_select_input(html)
        elif isinstance(self.widget, ClearableFileInput):
            html = self.fix_clearable_file_input(html)
        elif isinstance(self.widget, CheckboxInput):
            html = self.put_inside_label(html)
        return html
```

**Comment by dyve** [comment]
Thanks for the kind words!

**Comment by dyve** [comment]
Might do this at some point, keeping this issue for now. Just don't want to add too much new stuff when phasing out older settings.

**Comment by dblado** [comment]
+1 -- I can't see anyway to do https://getbootstrap.com/docs/3.3/css/#inline-checkboxes-and-radios w/out forking

**Comment by dblado** [comment]
On further research, it looks like this could be a bug. Bootstrap checkboxes and radios get their own \<label\> tag. The way django-bootstrap renders is w/ an outer \<label\> on the .form-group and inner \<label\> for each checkbox/radio. Bootstrap does not have a .form-group \<div\> on checkbox/radio groups.

from: https://getbootstrap.com/docs/3.3/css/#forms-example

```
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
```

**Comment by dyve** [comment]
Somehow this is still open, note to self to check if this can be fixed.
