### ISSUE TITLE
demo runserver don't work with Django >= 1.9

### ISSUE THREAD

**Issue by xoac** [dyve/django-bootstrap3#303]
Hi, I am new in Django and can't manage with this problem.

When I runserver from demo folder i get Error:
> TemplateSyntaxError at /
> 'url' is not a valid tag or filter in tag library 'future'

I found [that](http://stackoverflow.com/questions/31624606/error-when-django-with-rest-framework-deployed/31624759#31624759):
> ssi and url template tags will be removed from the future template tag library (used during the >1.3/1.4 deprecation period).

So i think it is a bug.

**Comment by dyve** [comment]
Which versions (Python, Django, django-bootstrap3) are you using?

**Comment by xoac** [comment]
Python3, Django 1.9.1 and  django_boostrap3 from github.

**Comment by dyve** [comment]
Thanks, confirmed

**Comment by dyve** [comment]
Fixed in develop branch
