### ISSUE TITLE
Add Subresource Integrity attribute in template tags includes

### ISSUE THREAD

**Issue by Alex131089** [dyve/django-bootstrap3#304]
More explanation on https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/ & https://www.srihash.org/ :)

Maybe as an option (which default to True) ?

**Comment by dyve** [comment]
Pull request welcome.

**Comment by dyve** [comment]
Checks fail, and I am not quite sure this is widely supported. This could be lack of knowledge on my part, but I don't want to release a version that breaks for a majority of users (like when we added `async` attribute). So I'm monitoring this with interest until checks pass and I know more. Thanks!

**Comment by Alex131089** [comment]
I don't know if it can breaks usage, but from what I see it's only a supplementary attribute, which the browser will takes if it knows it and ignore it otherwise ; I saw major websites using this so I guess there's no problem with it.
I fixed the indent issue ; still it doesn't pass because I didn't adapted tests.
But as a dictionnary (which is unordered) is passed to the tag builder for attributes, I guess that OrderedDict should be used instead ? Or is the test system smart enough to handle that (I don't have a lot of experience with tests) ?

**Comment by dyve** [comment]
Thanks! I'll look at the tests for the next release.

**Comment by dyve** [comment]
Closed via #344
