### ISSUE TITLE
Soon dropping support for Django < 1.8, Python < 2.7

### ISSUE THREAD

**Issue by dyve** [dyve/django-bootstrap3#308]
I think we did a wonderful job keeping old versions looped in. Now the time has come to let go of unsupported Django versions.

Soon we will go to version 7.x.x of `django-bootstrap3`. This will require Django >= 1.8 and Python >= 2.7.

If you need support for older projects, require `django-bootstrap3<7`

**Comment by dyve** [comment]
This issue wil remain open until 7.x.x is published on master / PyPI.

Please refer all complaints and suggestions about dropping support for older python and Django versions to this ticket, so we can discuss here.

**Comment by jieter** [comment]
[Django support for 1.7 already ended](https://www.djangoproject.com/download/#supported-versions), So I'd say you don't have to wait. Users stuck on 1.7 can continue to use `6.x.x`.

**Comment by dyve** [comment]
I'm just keeping this open until I publish 7.0.0.

**Comment by dyve** [comment]
7.0.0 is already out there.
