### ISSUE TITLE
No content visible.

### ISSUE THREAD

**Issue by aeroaks** [dyve/django-bootstrap3#312]
I am using Django 1.9 and demo template structure to display home.html.
I have included the following in the base.html file:
```
{% block bootstrap3_content %}
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
    ...
    </div>
  </nav>
  <div class="container-fluid">
  {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
  {% block content %}(no content){% endblock %}
  </div>
{% endblock %}
```
Navbar shows successfully but I do not get the Bootstrap message in the container below?
I am a new user to Django and this App as well. Please help!

**Comment by dyve** [comment]
Instructions for setting up Django messages are here:
https://docs.djangoproject.com/ja/1.9/ref/contrib/messages/

If this doesn't help you, please ask on StackOverflow (http://stackoverflow.com)
