### ISSUE TITLE
 from .exceptions import BootstrapError

### ISSUE THREAD

**Issue by bwlab2016** [dyve/django-bootstrap3#316]
File "C:\Users\Seth\Desktop\django-bootstrap3-develop\bootstrap3\tests.py", line 13, in <module>
    from .exceptions import BootstrapError
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by dyve** [comment]
Thanks for reporting. The tests run fine both locally and on Travis. For now this looks like something in your local environment. From the path it looks like you are running the tests from a folder on a Windows desktop. It could be that Python paths etc. are not properly set, but it's just a guess, I have no experience running Python on Windows.
