### ISSUE TITLE
Checkboxes should not use input-{sm,lg}

### ISSUE THREAD

**Issue by cybojenix** [dyve/django-bootstrap3#318]
according to https://github.com/twbs/bootstrap/issues/18748, checkboxes are not form-control elements, and so should not use input-{sm,lg}.

http://jsbin.com/habufaxike/edit?html,output

as can be seen, the form-group does not grow to contain the checkbox label (as the height is set to `@input-height-{small,large}`

suggest changing https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/renderers.py#L396 to 
```python
    def wrap_widget(self, html):
        if isinstance(self.widget, CheckboxInput):
            html = '<div class="checkbox">{content}</div>'.format(
                content=html,
            )
        return html
```

**Comment by dyve** [comment]
Nasty. Will look into it.

**Comment by dyve** [comment]
Thanks, fixed
