### ISSUE TITLE
[Question] use bootstrap paper theme for css 

### ISSUE THREAD

**Issue by dmsherazi** [dyve/django-bootstrap3#319]
I would like to use [paper theme](https://bootswatch.com/paper/) for bootstrap. What is the best way to achieve this css

**Comment by ikcam** [comment]
Add the CSS URL to the [BOOTSTRAP3 settings](http://django-bootstrap3.readthedocs.org/en/latest/settings.html).

**Comment by dmsherazi** [comment]
Where is the `settings.py` file located in nsupdate?
