### ISSUE TITLE
Issues with loading bootstrap_css and bootstrap_javascript

### ISSUE THREAD

**Issue by Jzarecta** [dyve/django-bootstrap3#321]
The application is causing isssues when loading the bootstrap_css on the template. The Quick setup mentioned on the doc fail when loading any other tag than bootstrap3. Saying that no such tag exist. Is there something that needs to  be declared somewhere else?

**Comment by ikcam** [comment]
Maybe is missing this line one your template:

{% load bootstrap3 %}

**Comment by Jzarecta** [comment]
I did had load bootstrap3 and **then** load bootstrap_css similar to the quick example here:
http://django-bootstrap3.readthedocs.org/en/latest/quickstart.html#example-template
http://i.imgur.com/9ENCYqb.png

**Comment by ikcam** [comment]
You are using incorrectly the tag is suppossed to be:
`{% bootstrap_css %} `

And you are using :
`{% load bootstrap_css %} `
