### ISSUE TITLE
django-filter parameters not passed to n+1 pages

### ISSUE THREAD

**Issue by rbonthond** [dyve/django-bootstrap3#323]
when using bootstrap_pagination in the html, additional parameters, like used by django-filter, aren't passed on the links for n+1 pages.

**Comment by ikcam** [comment]
I suggest you to use a custom tag for the pagination such as this:

```python
@register.simple_tag
def url_replace(request, field, value):
	dict_        = request.GET.copy()
	dict_[field] = value
	return dict_.urlencode()
```

And on your template:
```html
<li class="next"><a href="?{% url_replace request 'page' page_obj.next_page_number %}">Next <span aria-hidden="true">&rarr;</span></a></li>
```

**Comment by rbonthond** [comment]
I did something like this


```
from bootstrap3.templatetags.bootstrap3 import get_pagination_context
from django import template

register = template.Library()

@register.inclusion_tag('bootstrap3/pagination.html', takes_context=True)
def filtered_pagination(context, page):
    request = context['request']
    extra = "&".join(["%s=%s" % (k, v) for k, v in request.GET.items() if k != 'page'])
    pagination_kwargs = {'extra': extra, 'page': page}
    return get_pagination_context(**pagination_kwargs)
```

and then in my template:

```
{% load filtered_pagination %}
{% block pagination %}
    {% filtered_pagination table.page %}
{% endblock pagination %}
```

could something like this be done default? I'm guessing other people will run into the same issue

**Comment by suriya** [comment]
django-bootstrap-pagination https://github.com/jmcclell/django-bootstrap-pagination handles this properly. django-bootstrap3 copying this implementation would be ideal.

**Comment by adriaant** [comment]
This is open source, feel free to make a pull request.

**Comment by dyve** [comment]
It was actually a bit more complex, since we allow you to specify a custom url. I took function from urllib (will probably have to fix some Python3 compat issues) and let those handle the url. Please see if the development version meets your needs. Also, some test cases would be more than welcome (through PR).
