### ISSUE TITLE
global set_required=False overwrites local set_required=True

### ISSUE THREAD

**Issue by karyon** [dyve/django-bootstrap3#325]
because of this line: https://github.com/dyve/django-bootstrap3/blob/ae460aa6bc23bb49e8b6b85e12617983a9c162f1/bootstrap3/forms.py#L167 there is no chance to set `set_required` to `True` on single forms/fields if the global setting is `False`. I would expect the global setting to set a default which can be overridden locally.

I'd make a pull request if you can confirm this is not intended behavior.

**Comment by dyve** [comment]
This settings will probably be gone or at least severely rewritten because of #337. I'd appreciate any insights you have on that issue.

**Comment by dyve** [comment]
Closing this one, please discuss at #337.
