### ISSUE TITLE
documentation error bootstrap_label 

### ISSUE THREAD

**Issue by bsherrill480** [dyve/django-bootstrap3#332]
It looks like the "for" in the bootstrap_label example should be "label_for"
i.e.
`{% bootstrap_label "Email address" for="exampleInputEmail1" %}`
should be
`{% bootstrap_label "Email address" label_for="exampleInputEmail1" %}`

http://django-bootstrap3.readthedocs.io/en/latest/templatetags.html#bootstrap3.templatetags.bootstrap3.bootstrap_label

**Comment by dyve** [comment]
You are correct.
