### ISSUE TITLE
Django 1.9 and disabled form fields

### ISSUE THREAD

**Issue by dyve** [dyve/django-bootstrap3#345]
Note that Django 1.9+ can handle HTML `disabled` attribute.
https://docs.djangoproject.com/el/1.10/ref/forms/fields/#disabled
See #337 for HTML `required` in Django 1.10+.

I suggest removing both `set_required` and `set_disabled` and leave the setting of HTML attributes to Django.

**Comment by cybojenix** [comment]
This is a breaking change for users of 1.8 LTS, which does not support setting required/disabled attributes

**Comment by dyve** [comment]
Yes. But leaving it it for only Django <= 1.8 would mean that a Django upgrade would change how django-bootstrap3 works. For 1.8 LTS projects, I'd advise settings requirements.txt to stay away from the next major version of django-bootstrap-3 (we use semver).

**Comment by dyve** [comment]
Change of mind. Let's keep the 1.8 LTS supported for now. New version in develop branch.

**Comment by cybojenix** [comment]
Looking at your commit, it might be ideal to support having `set_required|disabled` in all version, but show a warning of you use it on newer versions of django. 
People using this package in their own packages will need to support multiple versions too

**Comment by cybojenix** [comment]
Sorry I missed part of the code, you're already doing it. My bad

**Comment by dyve** [comment]
There is no warning, but my intention is to

- keep set_required / set_disabled in all versions for as long as 1.8 is supported
- ignore these settings and what they do from a certain Django version

For now it is <= 8 supports it, but I think I need to switch that to 1.0+ does NOT support it. Also, I'll change the name of the parameter.

**Comment by dyve** [comment]
Drew the line at 1.10.

Django < 1.10 - set_required and set_disabled work as usual (legacy support)
Django >= 1.10 set_required and set_disabled are ignored, no way to activate them (roadmap)
