### ISSUE TITLE
Deploying to Google App Engine throws error

### ISSUE THREAD

**Issue by Dnncha** [dyve/django-bootstrap3#348]
I'm getting an error after adding django-bootstrap3 to my app.yaml and deploying to Google App Engine.

`the library "django-bootstrap3" is not supported`

Everything runs fine locally. Any idea if there are any tweaks that could get this running on GAE?

Thanks for your work.

**Comment by dyve** [comment]
I think you'd best ask this question on StackOverflow.com <http://stackoverflow.com/>.

**Comment by Dnncha** [comment]
I realised I didn't need this package, django widgets had all I needed. Thanks!
