### ISSUE TITLE
How to use local bootstrap?

### ISSUE THREAD

**Issue by cl0ne** [dyve/django-bootstrap3#350]
Of course, I can override `css_url` with hardcoded URL. But how to use `static` tag to get css file url without overriding whole `bootstrap3.html` template?

**Comment by ikcam** [comment]
You can override the `css_url` on the `settings.py`file of your project without any hardcode.

**Comment by jieter** [comment]
@ikcam I think @cl0ne tries to ask how to get an url to the location of a static file in the `css_url`, which could be hard-coded.

You might succeed in doing it automatically, but you'll need some lazy approach: generating the url will require some settings to be defined so it cannot be returned as a string from a function ran in settings.py if that makes sense...

**Comment by cl0ne** [comment]
It's not possible to use `static` within `settings.py`. How can I get something equivalent to
```
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
```

**Comment by cl0ne** [comment]
@jieter You're right. Probably some wrapper with `__str__` method will be sufficient, going to try this approach.

**Comment by cl0ne** [comment]
Thanks @jieter for idea! Came up with the following approach:
```py
class StaticWrapper:
    def __init__(self, path):
        self.path = path

    def __str__(self):
        return static(self.path)

BOOTSTRAP3 = {
    'css_url': StaticWrapper('bootstrap/dist/css/bootstrap.min.css')
}
```

**Comment by dyve** [comment]
Good solution @jieter. But this could use a better fix, I'll look at examples form Django static urls to see if we could just apply `static` to the url.

**Comment by gaelanadams** [comment]
@cl0ne did you define your class in your settings.py or another file? 

@dyve Sorry I'm new to django would using staticfile prefixes work?

**Comment by cl0ne** [comment]
@gaelanadams I define it in separate file and then import in `settings.py` (even though it's only used there, but don't think it's good idea to not put it in separate file).

**Comment by METAJIJI** [comment]
May be simply:
```
BOOTSTRAP3 = {
    'base_url': '%sbootstrap/' % STATIC_URL,
...
}
```

**Comment by dyve** [comment]
The most elegant solution would be if I ran the resulting url through static.

```
from django.contrib.staticfiles.templatetags.staticfiles import static
# Assume static path = '/static/'

url = static('bootstrap.css')
# url is now '/static/bootstrap.css'

url = static('https://example.com/bootstrap.css')
# url is now 'https://example.com/bootstrap.css'

url = static('/bootstrap.css')
# url is now '/bootstrap.css' -- so mind the starting slash
```

**Comment by melvyn-sopacua** [comment]
I don't see the upside to loading a template tag for this.
What use case is there, where this does not resolve to STATIC_URL + path?
And STATIC_URL should be right there in settings.py.

**Comment by dyve** [comment]
The original reason for a template tag was to make it easy to use the same settings (JS, CSS, theme) in different templates. I agree that it's not a super big advantage, but it makes getting started easier.

**Comment by melvyn-sopacua** [comment]
It's a documentation issue. People perceive the static template tag as magical, yet all it does is put STATIC_URL before the argument.
This:
```python
BOOTSTRAP3 = {
    'css_url': StaticWrapper('bootstrap/dist/css/bootstrap.min.css'),
    'jquery_url': StaticWrapper('jquery/dist/jquery.min.js'),
    'javascript_url': StaticWrapper('bootstrap/dist/js/bootstrap.min.js'),
}
```
and this:
```python
BOOTSTRAP3 = {
    'jquery_url': STATIC_URL + 'js/jquery.min.js',
    'css_url': STATIC_URL + 'css/bootstrap.min.css',
    'javascript_url': STATIC_URL + 'js/bootstrap.min.js',
}
```
is no different to the end user, except that the first creates a circular dependency in the boot cycle of Django and loads a bunch of code. Solve this in the documentation, not the code.

Now, if you want to make things easy on end users, then support something like:
```python
BOOTSTRAP3 = {
    'css_url': 'css/bootstrap.min.css',
    # ....
    'urls_static': True,
}
```
This avoids the circular dependency as you'd only have to transform them once one of the template tags is called and can simply defer to the static tag.

**Comment by cl0ne** [comment]
> People perceive the static template tag as magical, yet all it does is put STATIC_URL before the argument.

> The builtin template tag static which takes a path and urljoins it with the static prefix STATIC_URL.
>
> If django.contrib.staticfiles is installed, the tag uses the url() method of the STATICFILES_STORAGE instead.
