### ISSUE TITLE
Add subresource integrity

### ISSUE THREAD

**Issue by dyve** [dyve/django-bootstrap3#355]
See #353 for a good attempt that backfired.

I'd like subresource integrity, but easily configurable and no hassle for those using local Bootstrap files.

**Comment by dkinon** [comment]
I understand the complexities of managing sub-resource integrity in the previous solution (#353).  Maybe I'm missing some greater context but a sufficient middle ground could be to make enabling integrity a globally explicit option (disabled by default).  Then those that don't have these issues (me included) have a global solution and those that don't care about or actively want to avoid integrity can do so by default.

**Comment by dyve** [comment]
We implemented this on the Bootstrap 4 version, will see if we can port it to Bootstrap 3.

```
'css_url': {
        'href': "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css",
        'integrity': "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ",
        'crossorigin': "anonymous",
    },
```

**Comment by dyve** [comment]
Bump
