### ISSUE TITLE
support for Django 1.11

### ISSUE THREAD

**Issue by jannh** [dyve/django-bootstrap3#356]
File "*******/lib/python3.4/site-packages/bootstrap3/templatetags/bootstrap3.py", line 16, in <module>
    from ..components import render_icon, render_alert
  File "*******/lib/python3.4/site-packages/bootstrap3/components.py", line 4, in <module>
    from django.forms.widgets import flatatt
ImportError: cannot import name 'flatatt'

**Comment by cybojenix** [comment]
```python
from django.forms.utils import flatatt
```
This is "backwards compatible" to django 1.7, however it is undocumented.

**Comment by MinghaoLee** [comment]
Thanks a lot! :+1:

**Comment by okgao** [comment]
I use django2.0.2 and bootstrap3. The default of bootstrap3 is `from django.forms.utils import flatatt`.
I also meet question:

> 

> 
> 
> Request Method: | GET
> -- | --
> https://mighty-harbor-16554.herokuapp.com/
> 2.0.2
> InvalidTemplateLibrary
> Invalid template library specified. ImportError raised when trying to load 'bootstrap3.templatetags.bootstrap3': cannot import name 'flatatt'
> /app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py in get_package_libraries, line 125
> /app/.heroku/python/bin/python
> 3.6.4
> ['/app',  '/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python36.zip',  '/app/.heroku/python/lib/python3.6',  '/app/.heroku/python/lib/python3.6/lib-dynload',  '/app/.heroku/python/lib/python3.6/site-packages']


Who can tell me how to do ?
