### ISSUE TITLE
.pyc in pypi package

### ISSUE THREAD

**Issue by invenis-paris** [dyve/django-bootstrap3#365]
Hello,
The pypi package version 8.1.0 contains the .pyc files
They were not present in previous packages and now causes some packaging issues.
is it possible to remove them ?

Regards

**Comment by dyve** [comment]
That's weird, shouldn't happen. Will look into it.

**Comment by dyve** [comment]
It was a bug in setuptools.

I have added a global exclude in the newest release to make sure it can't effect django-bootstrap3 again.

**Comment by invenis-paris** [comment]
Cool. Thank you !

**Comment by auvipy** [comment]
it's solved please close the issue
