### ISSUE TITLE
Labels not being localized in forms

### ISSUE THREAD

**Issue by diogobaeder** [dyve/django-bootstrap3#368]
Hey guys,

First of all, great project! It's helping me a lot with a website I'm developing.

There's an issue, though: I'm localizing the website to "pt-BR", and the labels for the forms I place in the templates with `{% bootstrap_form form %}` are not being localized, even though the models that feed the ModelForm subclasses have internationalized fields (like `verbose_name=_('Name')` and so on).

Am I doing something wrong? Or is this an expected limitation from django-bootstrap3? Or perhaps a genuine bug?

Thanks!

**Comment by dyve** [comment]
Hi, sorry for the late reply. This is strange, can you confirm that a form renderen by Django `{{ form.as_p }}` *does* show the localized labels?
