### ISSUE TITLE
Import error for flatatt using upcoming Django 1.11

### ISSUE THREAD

**Issue by Macainian** [dyve/django-bootstrap3#369]
In utils.py and components.py there is an import for flatatt as:
from django.forms.widgets import flatatt

but https://docs.djangoproject.com/en/1.10/_modules/django/forms/widgets/ says it should be:
from django.forms.utils import flatatt

I tested and the import error goes away if you change it to that. This is on Django 1.11. Perhaps the import using widgets was a redundancy of utils for backward compatibility? I mean it is in the 1.10 docs using utils.

**Comment by goodtune** [comment]
The correct import has been `from django.forms.utils` since version 1.8 of Django.

Regardless, this was fixed in 853d499.

**Comment by Macainian** [comment]
Ah indeed, strange that it's been working with up to and including Django 1.10. When will this be available on pypi? 8.1.0 doesn't have this.

**Comment by adamcharnock** [comment]
It'd be great to see a release of this as Django 1.11b1 has just come out.

**Comment by goodtune** [comment]
When 1.11 is released, we can adjust our testing regime to exclude 1.9 and add 1.11. At that time, the supported versions of Django will be 1.8LTS, 1.10, and 1.11LTS.

https://www.djangoproject.com/download/#supported-versions

**Comment by auvipy** [comment]
1.9 support doesn't need to be removed. but badly need 1.11b1 support

**Comment by dyve** [comment]
Closed because this was fixed in 853d499. Adding tests for Django 1.11 now. When tests pass, I'll push to PyPI.
