### ISSUE TITLE
Add tag for CDN links with fallback

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#373]
For inspiration you can have a look at http://stackoverflow.com/questions/26192897/should-i-use-bootstrap-from-cdn-or-make-a-copy-on-my-server and http://eddmann.com/posts/providing-local-js-and-css-resources-for-cdn-fallbacks/

**Comment by dyve** [comment]
Interesting technique, but we'll leave this up to individual users to implement.
