### ISSUE TITLE
django.utils.importlib error

### ISSUE THREAD

**Issue by D-K-E** [dyve/django-bootstrap3#377]
Using Django 1.10.5 and django-bootsrap3 4.11.0     
I was having the following error:      
`Invalid template library specified. ImportError raised when trying to load 'bootstrap3.templatetags.bootstrap3': No module named 'django.utils.importlib'`

When i commented out the `django.utils.importlib` section and added the `from importlib import import_module` issue disappears

**Comment by machira** [comment]
Try updating to a newer version of django-bootstrap3. I was looked at the releases on here: https://github.com/dyve/django-bootstrap3/releases and saw that they have released up to version 8.2.3. This one doesn't throw this particular error.

**Comment by jieter** [comment]
@D-K-E I'm closing this, please update and reopen if the issue persists.
