### ISSUE TITLE
Feature request: Please add option to control error messages in bootstrap_fom

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#380]
The `bootstrap_form` tag renders output equivalent of `bootstrap_form_errors`. The messages from my fields also appear in the top messages, which is a bit redundant. It would be nice if I could do `{% bootstrap_form form errors_type='non_fields' %}` and/or set the default behaviour in settings.

**Comment by cybojenix** [comment]
hey, we hit the same issue. We use a custom renderer to force non_fields to be default (though I realise that this may not be what everyone wants).

```python
# bootstrap3_renderers.py
from bootstrap3.renderers import FormRenderer
class CustomFormRenderer(FormRenderer):
    def render_errors(self, type='non_fields'):
        # We have changed the default type to non_fields
        return super().render_errors(type=type)

# settings.py
BOOTSTRAP3 = {
    'form_renderers': {
        'default': 'app_name.bootstrap3_renderers.CustomFormRenderer',
    },
}
```

I assume the same logic can be applied to formsets

**Comment by dyve** [comment]
Fixed, thanks!
