### ISSUE TITLE
No HTML5 attributes?

### ISSUE THREAD

**Issue by silentjay** [dyve/django-bootstrap3#382]
As far as I can see there's no way of adding HTML5 attributes to the fields markup currently, such as "min" and "max", is that correct?

**Comment by ikcam** [comment]
You can add them in your `forms.py` file.

For example:
```
class Form(forms.Form):
  number = forms.IntegerField(max_value=5, min_value=0)
```
This will render an HTML5 field.

**Comment by silentjay** [comment]
Ah brilliant thank you
