### ISSUE TITLE
Placeholder not added with Django 1.11

### ISSUE THREAD

**Issue by cybojenix** [dyve/django-bootstrap3#387]
I've just stumbled into it locally, so not had chance to investigate.

Basically, with Django 1.11, the placeholders aren't being added to the output.

We rely on the default behaviour of adding the placeholder from the label.

A basic version of our usecase:

```python
# forms.py

class SomeForm(forms.Form):
    some_field = forms.IntegerField(label="This is the label", help_text="this field is for things")
```

```html
# page.html
{% load bootstrap3 %}

{% bootstrap_field some_form.some_field show_help=False %}
```

I'll investigate further in a bit, and probably write a fix.

output of what I had (the top one is just a text field):
![pasted image at 2017_04_06 12_49](https://cloud.githubusercontent.com/assets/2099618/24753609/bcf0b204-1aca-11e7-9f3a-38d7c2651303.png)

**Comment by cybojenix** [comment]
https://github.com/cybojenix/django-bootstrap3/tree/fix-placeholder

**Comment by dyve** [comment]
Can you submit the fix as a Pull Request on the develop branch? Thanks!

**Comment by cybojenix** [comment]
@dyve it's not a fix yet. it's just a test case, posting it here for tracking purposes is all.

Will be a PR when fixed

**Comment by dyve** [comment]
Ah, wishful thinking on my part, apologies! Will look before replying next time :-)

**Comment by dyve** [comment]
Thanks to everyone that helped with this!
