### ISSUE TITLE
Jquery UI slider doesn't work

### ISSUE THREAD

**Issue by bene25** [dyve/django-bootstrap3#390]
How could I implement jQuery UI slider or something similar?
For now if I extending from base template Jquery UI sample (https://jqueryui.com/slider/) wont work. If I don't extend from base html everything works. 
Django 1.10.3.

**Comment by dyve** [comment]
Hi, it looks like you might need some help getting set up. The best place to ask for help is [StackOverflow](https://stackoverflow.com). Please try to get your answer there.
