### ISSUE TITLE
Make it possible to change the close button on messages

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#395]
In a project I am working on, we generally use a font-awesome icon instead of a mere `x` as the close button for messages. I can also imagine that in some cases you would be better to use a translated string.
Therefore I propose to make it possible to change the content of the close button, and do it in a way that supports a translatable string or html, such that the following two scenarios are supported;
```
BOOTSTRAP3 = {
    'message_close_button': '<i class="fa fa-times-circle"></i>'
}
```
and
```
BOOTSTRAP3 = {
    'message_close_button': _('close')
}
```

**Comment by dyve** [comment]
Apologies for the late reply.
I can see this being a good addition. @beruic could you make a PR?

**Comment by beruic** [comment]
I'll see if I can make time for looking into it next week :)

**Comment by beruic** [comment]
Reviewing this, you had nothing to be sorry about @dyve :)
I however went way overdue because of some changes in my job situation.

Now, I'm not saying that I will make a PR for this, since Bootstrap 4 has happened, but if anyone  would be interested I would like to give it a try. However, for now i will leave it up to @dyve whether it should be closed or not.

**Comment by dyve** [comment]
Thanks @beruic. Since there has been no response to this feature, I'd not put too much time into it.
