### ISSUE TITLE
Define "Selected"

### ISSUE THREAD

**Issue by Tom-Gorup** [dyve/django-bootstrap3#396]
Is it possible to define the selected field when using `bootstrap_field` that's an option field?

Example would be if I had a Django form of cars:
```
cars_options = (
    ('volvo', 'Volvo'),
    ('saab', 'Saab'),
    ('vw', 'VW'),
    ('audi', 'Audi'),
)

class CarsForm(forms.Form):
    car_type = forms.ChoiceField(required=True, choices=cars_options)
```

I understand I can do `initial='saab'` however I would like to be able to define that on the response. For example, return the information about the car and retain the user's selection.
```
    return render(request, 'cars_app/cars.html', {'form': form,
                                                  'car': selected_car,
                                                  'car_stats': car_stats})
```

So, I would like to be able to render it something similar to this (either the previous selection or None):

```
{% bootstrap_field form.car_type selected={{ car }}|None %}
```

HTML version of what I'm attempting to accomplish.

```
<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="vw">VW</option>
  <option value="audi" selected>Audi</option>
</select>
```

Please let me know if you need any additional info. Appreciate any assistance you can provide.

**Comment by ikcam** [comment]
You should define this on your `forms.py` file.

```
# forms.py
from django import forms


class MyForm(forms.Form):
    CAR_CHOICES = (
        ('volvo', 'Volvo'),
        ('saab', 'Saab'),
        ('vw', 'VW'),
        ('audi', 'Audi'),
    )
    car = forms.SlugField(choices=CAR_CHOICES)
```

**Comment by Tom-Gorup** [comment]
Sure, I have similar code in my question above. The issue I'm having is figuring out how to define what the user has already selected in the response as to retain that selection as further action is taken on the form.

Does that make sense?

**Comment by ikcam** [comment]
@Tom-Gorup if you want to do that you have to do it on the `forms.py` file as well.

```python
# forms.py
from django import forms


class MyForm(forms.Form):
    CAR_CHOICES = (
        ('volvo', 'Volvo'),
        ('saab', 'Saab'),
        ('vw', 'VW'),
        ('audi', 'Audi'),
    )
    car = forms.SlugField(choices=CAR_CHOICES, initial='vw')
```

**Comment by Tom-Gorup** [comment]
I guess I'm having trouble feeding the user's selection back into this class or defining it in the HTML form as the selected option upon response. This more than likely lack of knowledge than an issue based on your response. 

I'm attempting something similar to:

```
def __init__(self, user_selection):
    self. user_selection = user_selection

{...}

car = forms.SlugField(choices=CAR_CHOICES, initial=self.user_selection)
```

Something similar to this. Again, it's probably due to my lack of knowledge on how these classes are implemented, but the` __init__` doesn't quite work the way I understand it. 

Does that make sense?

Appreciate your patience as assistance!

**Comment by jieter** [comment]
This is an issue tracker to report bugs and request features, not a place to ask for help on using the library. This seems to be a django question not really related to django-bootstrap3 anyway.
Please use [stackoverflow](http://stackoverflow.com/questions/tagged/django-bootstrap3) and tag your question with `django-bootstrap3`
