### ISSUE TITLE
unable to apply filters to bootstrap_messages

### ISSUE THREAD

**Issue by MCBama** [dyve/django-bootstrap3#397]
According to documentation:

> bootstrap3/messages.html
> 
> This renders the Django messages variable.
> 
> Variable messages contains the messages as described in https://docs.djangoproject.com/en/dev/ref/contrib/messages/#displaying-messages
> 
> messages is passed through three built-in filters
> 
> safe <https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-safe>
> 
> urlize <https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-urlize>
> 
> linebreaksbr <https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-linebreaksbr>
> 

bootstrap messages is supposed to be automatically applying the safe, urlize, and linebreaksbr filters but this does not seem to be happening.  Creating a message of the format
`messages.success(request, 'Test message line 1\nTest message line 2')`
should produce a linebreak in the HTML via the linebreaksbr filter but it does not.

**Comment by ikcam** [comment]
This was already discussed at https://github.com/dyve/django-bootstrap3/pull/352

**Comment by jieter** [comment]
Please refer to the discussion in #352
