### ISSUE TITLE
RemovedInDjango21Warning: renderer argument to render() method

### ISSUE THREAD

**Issue by ChaosCA** [dyve/django-bootstrap3#402]
```site-packages\bootstrap3\renderers.py:546: RemovedInDjango21Warning: Add the `renderer` argument to the render() method of <class 'captcha.widgets.ReCaptcha'>. It will be mandatory in Django 2.1.
  html = self.field.as_widget(attrs=self.widget.attrs)```

**OS:** Windows 10

**Steps to reproduce:** Create a form with a recaptcha widget

**Comment by jieter** [comment]
@ChaosMTA thanks for the bug report. 

We'll look into it but Django 2.1 will be released in augustus 2018, so not a priority right now.

**Comment by zvolsky** [comment]
I propose for django-ajax-selects and django-colorfield to add new parameters to .render() method(s):
-- .render(......)
++ .render(......, renderer=None, **_kwargs)
Could it help here?

**Comment by filipp** [comment]
I think I just got bitten by this bug:
http://dpaste.com/1HCSAFJ

Tried with latest django-bootstrap3 from Github, but same problem.

**Comment by filipp** [comment]
I thought I was just bitten by this exact problem, but it turned out it was just my broken super() calls. Everything seems to work fine with Django 2.1.1 and django-bootstrap3. Should this issue be marked as Closed?

**Comment by dyve** [comment]
Yes, closing this. If someone can reproduce, please submit a test in PR, or at least copy/paste code to reproduce. Thanks all!
