### ISSUE TITLE
Demo app error: cannot find admin template widgets

### ISSUE THREAD

**Issue by zorun** [dyve/django-bootstrap3#403]
When running the demo app and accessing e.g. http://localhost:8000/form there is an error:

```
TemplateDoesNotExist at /form
admin/widgets/split_datetime.html
```

Adding `django.contrib.admin` to the `INSTALLED_APPS` of the demo project solved the issue.  This is using Django 1.11.1 with Python 2.7.

**Comment by arbego** [comment]
Hello, it says "No module named admindjango.contrib" when I add "django.contrib.admin" to the "INSTALLED_APPS". Any ideas?

**Comment by dyve** [comment]
Bug confirmed, will fix it in next release. Already fixed in the Bootstrap 4 version.

**Comment by dyve** [comment]
Has since been fixed, thanks for reporting.
