### ISSUE TITLE
Changing CSS classes

### ISSUE THREAD

**Issue by ChaosMTA** [dyve/django-bootstrap3#408]
Is it possible to change the CSS classes that this plugin adds? So I can add certain classes to some of the outputs for appearance changes?

**Comment by dyve** [comment]
There are options in the settings to do this.
http://django-bootstrap3.readthedocs.io/en/latest/settings.html <http://django-bootstrap3.readthedocs.io/en/latest/settings.html>

If this doesn't work for your use case, please be as specific as possible in describing what you would like to do.

**Comment by jieter** [comment]
@ChaosMTA I'm closing this for now, please reopen with more details if the settings do not fix your issue.
