### ISSUE TITLE
does this project support django 1.11?

### ISSUE THREAD

**Issue by asi14** [dyve/django-bootstrap3#410]
Hi, sorry for posting this question on  Issues, but I have a very quick question. Does this project support django 1.11? I've been looking to upgrade my version of django and I was checking up dependency issues.

**Comment by ikcam** [comment]
It does, you can check the tox file.

Irving Kcam
Python Developer

**Comment by jieter** [comment]
Yes, like @ikcam said, we test against all currently supported django versions.
