### ISSUE TITLE
error on line XX at column Y: Opening and ending tag mismatch: link line 0 and head

### ISSUE THREAD

**Issue by afrigeri** [dyve/django-bootstrap3#411]
I got the error from a django page using django-bootstrap3, it seems that the only 'open' tag is the one specifying the CSS.  Closing the 'link' tag fixes the error, and the page is displayed correctly.

Is it possible (via configuration file or code fix) to change the  close the link tag from:  

`<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">`
to:
`<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />`

Thanks

Alessandro

**Comment by dyve** [comment]
There seems to be some text and/or code missing from your bug report.
