### ISSUE TITLE
Features : Date / Time / DateTime Fields in Django can be render in Bootstrap DateTime pickers + has-feedback icons

### ISSUE THREAD

**Issue by Hideman85** [dyve/django-bootstrap3#413]
Hello

Can you implements DateTime fields with https://eonasdan.github.io/bootstrap-datetimepicker/
You can add configuration option to enable / disable this feature because it's not in Bootstrap but it's an addon.

And just add  `.has-feedback` and icons option that we can enable in `BOOTSTRAP3` http://getbootstrap.com/css/#callout-has-feedback-icon-accessibility

Exemple : http://i.imgur.com/c4gKE8t.png

Great continuation for your project ;)

**Comment by Hideman85** [comment]
Same thing for `django-simple-captcha` your version : 
```
<div class="col-md-9">
    <img alt="captcha" class="captcha" src="/captcha/image/55fc8d5b5197bd6292a0f8247405a49ea65ac5ab/">
    <input id="id_captcha_0" name="captcha_0" value="55fc8d5b5197bd6292a0f8247405a49ea65ac5ab" type="hidden">
    <input autocapitalize="off" autocomplete="off" autocorrect="off" id="id_captcha_1" name="captcha_1" spellcheck="false" type="text">
</div>
```
Bootstrap version : 
```
<div class="col-md-9">
    <div class="input-group">
        <input id="id_captcha_0" name="captcha_0" value="7b7d550b84b3487ab0e63c0349c5fc2408975a8f" type="hidden">
        <span class="input-group-addon">
            <img alt="captcha" src="/captcha/image/7b7d550b84b3487ab0e63c0349c5fc2408975a8f/" class="captcha">
        </span>
        <input class="form-control" autocapitalize="off" autocomplete="off" autocorrect="off" id="id_captcha_1" name="captcha_1" spellcheck="false" style="/*! height: 100%; */" placeholder="Captcha" type="text">
    </div>
</div>
```

**Comment by dyve** [comment]
We won't do external packages like date pickers.

The `has-feedback` looks like we could do better. We already have the success classes for fields, so we'd have to take a look at that too.

**Comment by dyve** [comment]
@Hideman85 I'm closing this ticket because it contains 2-3 separate requests. I'll open a new one so `has-feedback` won't be forgotten.
