### ISSUE TITLE
Label generated with show_label=False with checkbox

### ISSUE THREAD

**Issue by kutera** [dyve/django-bootstrap3#414]
{% bootstrap_field form.statut       form_group_class='col-md-6'  show_label=False  %}
The form.statut field is a checkbox
Html Result : 
&lt;div class="col-md-6">
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="checkbox">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            &lt;label for="id_statut">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;input name="statut" class="" required="" id="id_statut"  type="checkbox"> J'adhère aux 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;a href="url_statuts.pdf" target="_blank">statuts&lt;/a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            &lt;/label>
&nbsp;&nbsp;&nbsp;&nbsp;      &lt;/div>
&lt;/div>

show_label has no effect. The source of the issue is maybe: 
FieldRenderer.put_inside_label()  in post_widget_render() with CheckBoxInput (renderers.py)

**Comment by dyve** [comment]
Thanks, looks like a bug. You've done some investigating already. A Pull Request with a test case would be very welcome.

**Comment by donvito-pl** [comment]
The bug is real. 
Is the fix coming anytime soon?

**Comment by dyve** [comment]
@donvito-pl @kutera any chance you can submit a pull request for this?

**Comment by donvito-pl** [comment]
Will try to investigate, but odds of succeeding not that high :)

**Comment by nikolaysm** [comment]
"addon_before, label_class and field_class" also don't work with checkbox. 
So checkbox field is can't be used as custom field.

**Comment by nikolaysm** [comment]
@dyve  @donvito-pl
 It can be solved when adding "label_class=self.get_label_class()" to the function below
```
def put_inside_label(self, html):
        content = '{field} {label}'.format(
            field=html,
            label=self.label,
        )
        return render_label(
            content=mark_safe(content),
            label_for=self.field.id_for_label,
            label_title=escape(strip_tags(self.field_help)),
            label_class=self.get_label_class()
        )
```

**Comment by robslotboom** [comment]
@nikolaysm

This is hiding the checkbox to.

Maybe something like this:

```
def put_inside_label(self, html):
        content = '{field} {label}'.format(
            field=html,
            >>>> label=self.label if self.show_label else ''
        )
        return render_label(
            content=mark_safe(content),
            label_for=self.field.id_for_label,
            label_title=escape(strip_tags(self.field_help))
        )
```
