### ISSUE TITLE
Form widget DateField, but input is type="text"

### ISSUE THREAD

**Issue by ignacionf** [dyve/django-bootstrap3#415]
In the class view have a model with field "nacimiento" (aka "birth"). In method get_form i check if this field is a form.DateField, and yes! it's. But in template, {% bootstrap_form %} print a input with type="text":

```
form = super(ClienteUpdate, self).get_form(form_class=form_class)
print(form.fields['nacimiento'])
```
<django.forms.fields.DateField object at 0x7f67142df518>

In template:
`<div class="form-group"><label class="control-label" for="id_nacimiento">Fecha de nacimiento</label><input **type="text"** name="nacimiento" class="form-control" id="id_nacimiento" placeholder="Fecha de nacimiento" title="" /></div>
`

bootstrap3 version:
django-bootstrap3==9.0.0

**Comment by ikcam** [comment]
`type="date"` it's not supported by all browsers.

Anyway you can adjust this on your `forms.py` file this way:
```python
class ClientForm(forms.ModelForm):
  class Meta:
    model = Client
    widgets = {
      'birth': form.DateInput(attrs={'type': 'date'}, format="%Y-%m-%d"),
    }

**Comment by ignacionf** [comment]
Ok, tnks!

This works!

`form.fields['nacimiento'].widget = forms.DateInput(attrs={'type': 'date'}, format="%Y-%m-%d")
`
