### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by beruic** [dyve/django-bootstrap3#417]
With the release of Bootstrap v4.0.0-beta it raises the question whether the this project in the future will fork to a version for Bootstrap 4 (which seems already what https://github.com/bitkits/bootstrap4-django set out to do, with little work done however), or try work on supporting both versions.

Can someone elaborate on what to expect, and maybe update the readme with at statement regarding the matter?

**Comment by dyve** [comment]
The bitkits version is new for me.

We have a Bootstrap 4 version in the works at https://github.com/zostera/django-bootstrap4 <https://github.com/zostera/django-bootstrap4>.

**Comment by beruic** [comment]
Well then I guess the issue is something else. I found the bitkits version by following the documentation link on https://pypi.python.org/pypi/django-bootstrap4

**Comment by dyve** [comment]
~~The bitkits version is new for me.~~
UPDATE: No it isn't, see https://github.com/bitkits/bootstrap4-django/issues/1

We have a Bootstrap 4 version in the works at https://github.com/zostera/django-bootstrap4.

Full disclosure: I on't expect we'll start using BS4 on any of our projects for at least 6 months, so it's a good guess we'll keep focusing on BS3 until then.

**Comment by dyve** [comment]
> Well then I guess the issue is something else. I found the bitkits version by following the documentation link on https://pypi.python.org/pypi/django-bootstrap4

Yes, bitkits took that name :-( see bitkits#1

**Comment by beruic** [comment]
Yes. Just read it. Closing this one :)

**Comment by dyve** [comment]
@beruic Good idea to add a mention to the README. Done.

**Comment by beruic** [comment]
Please see PR #418
