### ISSUE TITLE
How to implement base?

### ISSUE THREAD

**Issue by ruipacheco** [dyve/django-bootstrap3#426]
I've implemented a form according to the docs but noticed there's no body element. In fact, only the form itself:

`b'\n\n\n\n<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">\n<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>\n\n\n\n\n\n\n<form action="" method="post">\n    <input type=\'hidden\' name=\'csrfmiddlewaretoken\' value=\'CHT77phzdc7yU5Ybj1nmxLlI9hEWA0g846ENEIa751zksf0lIUQ8zAQF4E8nRt4o\' />\n    <p><label for="id_first_name">First name:</label> <input type="text" name="first_name" maxlength="30" id="id_first_name" /></p>\n<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name" /></p>\n<p><label for="id_email">Email:</label> <input type="email" name="email" value="james.bond@gmail.com" maxlength="254" id="id_email" required /></p>\n<ul class="errorlist"><li>This field is required.</li></ul>\n<p><label for="id_password">Password:</label> <input type="text" name="password" maxlength="128" id="id_password" required /></p>\n    <input type="submit" value="Save" />\n</form>'`

Am I missing something that is implicit? I'm on the latest Django 2.0.

**Comment by jieter** [comment]
This is an issue tracker to report bugs and request features, not a place to ask for help on using the library. Please use [stackoverflow](https://stackoverflow.com/questions/tagged/django+twitter-bootstrap-3) and tag your question with `django` and `twitter-bootstrap-3`
