### ISSUE TITLE
field_class and label_class not copied from widget

### ISSUE THREAD

**Issue by biggosh** [dyve/django-bootstrap3#428]
Hi,

great work, before all. Thanks.

I'm trying to put only on some rows of the form 2 char fields (ie. name / surname), the other rows has only one field. To do this, I need for some fields to change the value of field_class and form_class.

My code for the form is something like:
```
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="submit"/>
</form>
```
The CharField is created as:
`self.fields['name'] = forms.CharField(label = mark_safe(label), 
                                                widget=forms.Widget(attrs={'field_class': 'col-md-5'}))`

Is this a bug or a feature? If it's a feature, how can I specify only for some fields a custom field_class?

thanks in advance
BG

**Comment by dyve** [comment]
This looks like abuse of the `attrs` kwarg to me, since it should apple HTML attrs and not (additional) CSS classes.

**Comment by dyve** [comment]
Maybe you could use `bootstrap_field` with the `field_class` argument?
http://django-bootstrap3.readthedocs.io/en/latest/templatetags.html#bootstrap-field
