### ISSUE TITLE
You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware

### ISSUE THREAD

**Issue by lightjl** [dyve/django-bootstrap3#430]
`cd demo`
`python ./manage.py runserver`

http://127.0.0.1:8000/

**Comment by miyamotok0105** [comment]
I got the same error.

**Comment by burlesco1970** [comment]
Same error for me with Django 2.0.2 under Windows

**Comment by dyve** [comment]
Was caused by old MIDDLEWARE_CLASSES notation. Thanks for reporting!
