### ISSUE TITLE
not able to retrive namespace and name url in template

### ISSUE THREAD

**Issue by rahul6612** [dyve/django-bootstrap3#432]
**my main url is:**
`url(r'^posts/', include("posts.urls", namespace="posts")),`

**my app url is:**
`url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),`

i am trying to access it in my template like this:
` <small> <a href='{% url 'posts:update' %}'>***</a></small>`

**and getting this error:**
NoReverseMatch at /
Reverse for 'update' with no arguments not found. 1 pattern(s) tried: ['posts/(?P<pk>\\d+)/update/$']

**Comment by dyve** [comment]
This error is not connected to `django-bootstrap3`. Try StackOverflow or the Django docs.

**Comment by rahul6612** [comment]
ok thanks
