### ISSUE TITLE
Allow {% bootstrap_field exclude argument to be a list.

### ISSUE THREAD

**Issue by jieter** [dyve/django-bootstrap3#433]
I have a form with basic / advanced fields. I have a list of advanced field names defined on the form and a property returning all the basic field names, so I can render the fields like so:

```
{% bootstrap_form form exclude=form.advanced_fieldnames %}
{% bootstrap_form form exclude=form.basic_fieldnames %}
```

However, the exclude parameter must be a comma separated string of field names, and passing a list of field names makes it complain: `'list' object has no attribute 'replace'`.

I currently use `{% bootstrap_form form exclude=form.basic_fieldnames|join:',' %}` as a workaround, but it would be nice if that was not required.

**Comment by dyve** [comment]
Sounds like a plan.

**Comment by jieter** [comment]
hmm, still sounds like a plan to me.
