### ISSUE TITLE
Not able to customize the fields in a form when using {% bootstrap_form form %}

### ISSUE THREAD

**Issue by ImanoWilliams** [dyve/django-bootstrap3#440]
I am trying to render a form with the fields' sizes having specific length. When I use django-bootstrap3 **{% bootstrap_form form %}**, all the fields have the same size.

**Comment by ikcam** [comment]
You have to iterate field by field and inside of each field specify the size:

```html
{% for field in form.visible_fields %}
  {% bootstrap_field field %} 
{% endfor %} 

Also you can achieve this on your `forms.py` file:

```python
class Form(forms.Form):
  name = forms.CharField(widget=forms.TextInput(attrs={'size': 50}))
```
