### ISSUE TITLE
Python 3 - Solution error: Function "url_to_attrs_dict" expects a string or a dict with key "url".

### ISSUE THREAD

**Issue by briciosm1210** [dyve/django-bootstrap3#460]
#Fix bootstrap.py
Please correct the file!

def get_bootstrap_setting(setting, default=None):
    """
    Read a setting
    """
    value = BOOTSTRAP3.get(setting, default)
    return value if value else BOOTSTRAP3_DEFAULTS.get(setting)

**Comment by dyve** [comment]
Thanks for reporting this. I cannot reproduce any error that looks like this. Can you provide a failing test?
