### ISSUE TITLE
v12.0.0 removes bootstrap3.__version__

### ISSUE THREAD

**Issue by wummel** [dyve/django-bootstrap3#468]
The `__version__` attribute has been removed in 12.0.0 from the bootstrap3 module.
This is backwards incompatible and results in errors for apps using the version info.
Tested with 12.0.0 on Linux:
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bootstrap3
>>> bootstrap3.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bootstrap3' has no attribute '__version__'
```

11.1.0 works fine:
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bootstrap3
>>> bootstrap3.__version__
'11.1.0'
```

**Comment by dyve** [comment]
Thanks, the internal `__version__` attribute was indeed removed due to the switch to using git tags as versions. This was not part of the public API so we did not consider this a backwards incompatible change.

**Comment by wummel** [comment]
I see. It would be nice to have the version info back so that there is an easy way for applications to query and display it. So consider this ticket a feature request instead :-)

There is also a Python PEP 396 for modules providing version information, see https://www.python.org/dev/peps/pep-0396/
Re-adding the version attribute would implement that - like the 11.1.0 already did.

**Comment by dyve** [comment]
Proposed fix: https://github.com/zostera/django-bootstrap4/pull/186

**Comment by georgek** [comment]
Another solution is to use versioneer instead of setuptools_scm. This will allow you to access __version__ even when running from source code.

**Comment by dyve** [comment]
Thanks. The main goal of using setuptools_scm was to drop MANIFEST.in. Versioning with tags was a bonus, which we have now embraced. Looking at versioneer, I see no updates in the past 2 years and no support in CI for Python 3.7 and 3.8, so not something we'd consider right now.
