### ISSUE TITLE
dynamic tabs

### ISSUE THREAD

**Issue by damianlluch** [dyve/django-bootstrap3#475]
hello !, I need to have dynamic tabs manageable from the django administrator. With this project would you tell me how can I achieve it?

thanks!

**Comment by dyve** [comment]
Hi, it looks like you might need some help with a task related to this project. The best place to ask for help is [StackOverflow](https://stackoverflow.com). You will receive answers from a community of programmers!

If you ask your question on StackOverflow and use the tag `django-bootstrap3`, we'll be happy to reply over there with specific information. For questions about implementing a solution using this package, you may get help from fellow programmers.
